### ISSUE TITLE
Data2Volume: TypeError: order must be str, not int 

### ISSUE THREAD

**Issue by guanguanboy** [Vandermode/QRNN3D#5]
https://github.com/Vandermode/QRNN3D/blob/46e32e0e0678bdeefde952836057cbf0cd94d2ed/utility/lmdb_data.py#L29

(base) liguanlin@opt48:/mnt/liguanlin/Projects/QRNN3D$ /home/liguanlin/miniconda3/bin/python /mnt/liguanlin/Projects/QRNN3D/utility/util.py
Traceback (most recent call last):
  File "/home/liguanlin/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
TypeError: order must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/liguanlin/Projects/QRNN3D/utility/util.py", line 221, in <module>
    data = preprocess(mat['rad'])
  File "/mnt/liguanlin/Projects/QRNN3D/utility/util.py", line 85, in processor
    data = f(data)
  File "/mnt/liguanlin/Projects/QRNN3D/utility/util.py", line 61, in Data2Volume
    V[s1] = np.reshape(data[s2],-1,1)
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/liguanlin/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/liguanlin/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/liguanlin/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: order must be str, not int

**Comment by guanguanboy** [comment]
@Vandermode 
would you please share the correct Data2Volume function?
many thanks

**Comment by Vandermode** [comment]
This error is due to the backward compatibility issue of numpy. 
Have you addressed this issue?@guanguanboy

**Comment by guanguanboy** [comment]
> This error is due to the backward compatibility issue of numpy.
> Have you addressed this issue?@guanguanboy

Yes, you're right, it's a compatibility issue. I fix this by changing the sourcecode as follows:
def Data2Volume(data, ksizes, strides):
    """
    Construct Volumes from Original High Dimensional (D) Data
    """
    dshape = data.shape
    PatNum = lambda l, k, s: (np.floor( (l - k) / s ) + 1)    

    TotalPatNum = 1
    for i in range(len(ksizes)):
        TotalPatNum = TotalPatNum * PatNum(dshape[i], ksizes[i], strides[i])
    
    V = np.zeros([int(TotalPatNum)]+ksizes); # create D+1 dimension volume

    args = [range(kz) for kz in ksizes]
    for s in product(*args):
        s1 = (slice(None),) + s
        s2 = tuple([slice(key, -ksizes[i]+key+1 or None, strides[i]) for i, key in enumerate(s)])
        V[s1] = **np.reshape(data[s2],-1,1)**
        
    return V
